### ISSUE TITLE
Error when running build

### ISSUE THREAD

**Issue by amilcar-uptech** [geoenvo/oskari-application-bpn#4]
I get the following error in NPM logs when trying to run `npm run build -- --env.appdef=wbidp:applications`:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   '--env.appdef=wbidp:applications'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle wb-idp@1.2.1~prebuild: wb-idp@1.2.1
6 info lifecycle wb-idp@1.2.1~build: wb-idp@1.2.1
7 verbose lifecycle wb-idp@1.2.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle wb-idp@1.2.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/oskari/oskari-server/oskari-application-bpn/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle wb-idp@1.2.1~build: CWD: /opt/oskari/oskari-server/oskari-application-bpn
10 silly lifecycle wb-idp@1.2.1~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'node ./node_modules/oskari-frontend/node_modules/webpack/bin/webpack.js --config ./node_modules/oskari-frontend/webpack.config.js --mode production "--env.appdef=wbidp:applications"'
10 silly lifecycle ]
11 silly lifecycle wb-idp@1.2.1~build: Returned: code: 1  signal: null
12 info lifecycle wb-idp@1.2.1~build: Failed to exec build script
13 verbose stack Error: wb-idp@1.2.1 build: `node ./node_modules/oskari-frontend/node_modules/webpack/bin/webpack.js --config ./node_modules/oskari-frontend/webpack.config.js --mode production "--env.appdef=wbidp:applications"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid wb-idp@1.2.1
15 verbose cwd /opt/oskari/oskari-server/oskari-application-bpn
16 verbose Linux 5.4.0-1042-gcp
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--" "--env.appdef=wbidp:applications"
18 verbose node v12.22.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error wb-idp@1.2.1 build: `node ./node_modules/oskari-frontend/node_modules/webpack/bin/webpack.js --config ./node_modules/oskari-frontend/webpack.config.js --mode production "--env.appdef=wbidp:applications"`
22 error Exit status 1
23 error Failed at the wb-idp@1.2.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
This happens when I run it directly from the `oskari-application-bpn` folder, or when using the ansible from [ansible-onedataportal](https://github.com/geoenvo/ansible-onedataportal). I also tried removing the `package-lock.json` file, but it didn't seem to solve this.

**Comment by senoadiw** [comment]
Hi @amilcar-capsus, this should be fixed by https://github.com/geoenvo/ansible-onedataportal/commit/5662bd7d4776b59156f0ffb356eb50d853d9b657.

Since the dependency paths were updated in https://github.com/geoenvo/oskari-application-bpn/commit/593acc08bfe45bf28af95971f842920a80a1190b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R9, `npm run build -- --env.appdef=wbidp:applications` now expects `oskari-frontend` and `oskari-frontend-contrib` package directories under `/opt/oskari-server/oskari-application-bpn/node_modules` instead of previously under `/opt/oskari-server`.
